<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Bienvenido al SISTEMA INTEGRAL DE GESTI&Oacute;N DE ENTIDADES - CEDRUX</title>
<link href="<?php echo $this->dir_ext_ccs;?>css/ext-all.css" rel="stylesheet" type="text/css" media="screen"/>
</head>
<body  id="idbody">
  <table width="100%" height="100%">
    <tr><td align="center" valign="middle">
	    <div id="dFormIndex"><img src="views/images/index/logocedrux.png" style="position:absolute;width:180px;height:50px;background-color:#RRGGBB;margin:265px 0px 0px -10px;"></img></div>
	  </td></tr>
  </table>
  <input type="hidden" id="accesodirecto" value="<?php echo $this->accesodirecto;?>"/>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-base.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>
<script type="text/javascript" src="views/js/index/index.js"></script>
</body>
</html>