/*
 * File: Analizador.gpRespuesta.ui.js
 * Date: Thu Dec 31 2009 23:01:27 GMT-0800 (Pacific Standard Time)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file was manually exported.
 */

Analizador.UI.gpRespuesta = Ext.extend(Ext.grid.GridPanel, {
    title: 'Respuesta an&aacute;lisis',
    autoExpandColumn: 'analisis',
    initComponent: function() {
        this.btnRespuesta = new Ext.Button ({
            scope : this,
            text : 'Respuesta/DesRespuesta',
            disabled : true
        })
        
        this.store = new Ext.data.Store ({
           url : 'cargar',
           autoLoad : true,
           reader : new Ext.data.JsonReader({
               root : 'data'
           }, ['name', 'enabled'])
        })
        
        this.columns = [
            {
                dataIndex: 'name',
                header: 'An&aacute;lisis',
                sortable: true,
                id: 'analisis'
            },
            {
                dataIndex: 'enabled',
                header: 'Activado',
                sortable: true,
                renderer: this.checkRenderer
            }
        ];
        this.tbar = [
            this.btnRespuesta
        ];
        Analizador.UI.gpRespuesta.superclass.initComponent.call(this);
    }
});
