/*
 * File: WaoX.winConfiguration.ui.js
 * Date: Sat Jan 01 2011 00:01:02 GMT-0800 (Pacific Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('WaoX');
WaoX.winConfigurationUi = Ext.extend(Ext.Window, {
    height: 250,
    width: 400,
    title: 'Configuration',

    initComponent: function() {
        WaoX.winConfigurationUi.superclass.initComponent.call(this);
    }
});