/*
 * File: WaoX.stChart.js
 * Date: Sat Jan 01 2011 01:02:54 GMT-0500 (CST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('WaoX');
WaoX.stChart = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        WaoX.stChart.superclass.constructor.call(this, Ext.apply({
            storeId: 'waox.stChart',
            root: 'data',
            fields: [
                {
                    name: 'chart'
                },
                {
                    name: 'view'
                }
            ]
        }, cfg));
    }
});