/*
 * File: WaoX.cbView.ui.js
 * Date: Sat Jan 01 2011 01:02:54 GMT-0500 (CST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('WaoX');
WaoX.cbViewUi = Ext.extend(Ext.form.ComboBox, {
    displayField: 'name',
    mode: 'local',
    store: new WaoX.stView (),
    triggerAction: 'all',
    valueField: 'className',

    initComponent: function() {
        WaoX.cbViewUi.superclass.initComponent.call(this);
    }
});