/*
 * File: WaoX.vpWaox.ui.js
 * Date: Sat Jan 01 2011 00:04:14 GMT-0800 (Pacific Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('WaoX');
WaoX.vpWaoxUi = Ext.extend(Ext.Viewport, {
    layout: 'border',

    initComponent: function() {
        this.pCard = new Ext.Panel ({
            activeItem: 0,
            layout: 'card',
            scope: this,
            region: 'center',
            items: [
                {
                    xtype: 'waox.pBase', 
                    layout: 'fit',
                    scope : this,
                    id: 'splashScreen',
                    html: '<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><center><img src="../../images/WaoX.gif"/></center>',
                },
                {
                    xtype: 'waox.pBase',
                    scope : this,
                    id: 'placeHolder1',
                    layout: 'border',
                    items: {
                        region : 'center',
                        id : 'ph11',
                        html: '1'
                    }
                },
                {
                    xtype: 'waox.pBase',
                    scope : this,
                    id: 'placeHolder2',
                    layout: 'border',
                    items: [{
                        region : 'north',
                        id : 'ph21',
                        html: '1',
                        height: 384
                    },{
                        region : 'center',
                        html: '2',
                        id : 'ph22'
                    }]
                },
                {
                    id: 'placeHolder3',
                    scope : this,
                    xtype: 'waox.pBase',
                    layout: 'border',
                    items: [{
                        region : 'north',
                        id : 'ph31',
                        height: 384,
                        html: '1'
                    },{
                        region : 'center',
                        layout : 'border',
                        items  : [{
                            region : 'west',
                            id : 'ph32',
                            width: 512,
                            html: '2'
                        },
                        {
                            region : 'center',
                            id : 'ph33',
                            html: '3'
                        }]
                    }]
                },
                {
                    layout: 'border',
                    id: 'placeHolder4',
                    scope : this,
                    xtype: 'waox.pBase',
                    items: [{
                        region : 'north',
                        height: 384,
                        layout : 'border',
                        items  : [{
                            region : 'west',
                            id : 'ph41',
                            width: 512,
                            html: '1'
                        },
                        {
                            region : 'center',
                            id : 'ph42',
                            html: '2'
                        }]
                    }, {
                        region : 'center',
                        layout : 'border',
                        items  : [{
                            region : 'west',
                            id : 'ph43',
                            width: 512,
                            html: '3'
                        },
                        {
                            region : 'center',
                            id : 'ph44',
                            html: '4'
                        }]
                    }]
                }
            ]
        })

        Ext.applyIf(this, {
            items: this.pCard
        });

        WaoX.vpWaoxUi.superclass.initComponent.call(this);
    }
});