/*
 * File: WaoX.btnAdd.js
 * Date: Sat Jan 01 2011 00:02:54 GMT-0800 (Pacific Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

WaoX.btnAdd = Ext.extend(WaoX.btnAddUi, {
    initComponent: function() {
        WaoX.btnAdd.superclass.initComponent.call(this);
    }
});
Ext.reg('waox.btnAdd', WaoX.btnAdd);