/*
 * File: WaoX.btnRemove.ui.js
 * Date: Sat Jan 01 2011 00:02:54 GMT-0800 (Pacific Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('WaoX');
WaoX.btnRemoveUi = Ext.extend(Ext.Button, {
    text: 'Remove',
    disabled : true,

    initComponent: function() {
        WaoX.btnRemoveUi.superclass.initComponent.call(this);
    }
});