/*
 * File: WaoX.cbView.js
 * Date: Sat Jan 01 2011 01:02:54 GMT-0500 (CST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

WaoX.cbView = Ext.extend(WaoX.cbViewUi, {
    initComponent: function() {
        WaoX.cbView.superclass.initComponent.call(this);
    }
});
Ext.reg('waox.cbView', WaoX.cbView);