/*
 * File: WaoX.pBase.ui.js
 * Date: Sat Jan 01 2011 00:04:14 GMT-0800 (Pacific Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('WaoX');
WaoX.pBaseUi = Ext.extend(Ext.Panel, {
    frame: true,
    title: 'WaoX v0.1',

    initComponent: function() {
        this.btnNew = new WaoX.btnNew ({scope : this})
        this.winNew = new WaoX.winNew ({scope : this})

        Ext.applyIf(this, {
            tbar: {
                xtype: 'toolbar',
                items: [
                    {
                        xtype: 'button',
                        text: 'Dashboard',
                        menu: {
                            xtype: 'menu',
                            items: [
                                this.btnNew
                            ]
                        }
                    }
                ]
            }
        });

        WaoX.pBaseUi.superclass.initComponent.call(this);
    }
});