/*
 * File: WaoX.pBase.js
 * Date: Sat Jan 01 2011 00:04:12 GMT-0800 (Pacific Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

WaoX.pBase = Ext.extend(WaoX.pBaseUi, {
    initComponent: function() {
        WaoX.pBase.superclass.initComponent.call(this);

        this.btnNew.setHandler (function () {
        	this.winNew.show ()
        }, this)
    }
});
Ext.reg('waox.pBase', WaoX.pBase);