/*
 * File: WaoX.winNew.ui.js
 * Date: Sat Jan 01 2011 01:02:54 GMT-0500 (CST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('WaoX');
WaoX.winNewUi = Ext.extend(Ext.Window, {
    height: 304,
    width: 349,
    layout: 'border',
    title: 'New',
    modal: true,

    initComponent: function() {
        this.egChart = new WaoX.egChart ({scope : this})
        this.btnOk = new Ext.Button ({text : 'Ok', scope : this})
        this.btnCancel = new Ext.Button ({text: 'Cancel', scope : this})

        Ext.applyIf(this, {            
            items: [
                this.egChart
            ],
            buttons: [this.btnOk,
                      this.btnCancel]
        });

        WaoX.winNewUi.superclass.initComponent.call(this);
    }
});