/*
 * File: WaoX.btnNew.ui.js
 * Date: Sat Jan 01 2011 00:08:54 GMT-0500 (CST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('WaoX');
WaoX.btnNewUi = Ext.extend(Ext.menu.Item, {
    text: 'New',

    initComponent: function() {
        WaoX.btnNewUi.superclass.initComponent.call(this);
    }
});