/*
 * File: WaoX.btnNew.js
 * Date: Sat Jan 01 2011 00:08:54 GMT-0500 (CST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

WaoX.btnNew = Ext.extend(WaoX.btnNewUi, {
    initComponent: function() {
        WaoX.btnNew.superclass.initComponent.call(this);
    }
});
Ext.reg('waox.btnNew', WaoX.btnNew);