/*
 * File: WaoX.cbChart.js
 * Date: Sat Jan 01 2011 01:02:54 GMT-0500 (CST)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

WaoX.cbChart = Ext.extend(WaoX.cbChartUi, {
    initComponent: function() {
        WaoX.cbChart.superclass.initComponent.call(this);

        this.on ('select', function (pCB, pRecord, pIndex) {
        	this.selectedChart = pRecord.data.name
        }, this)
    }
});
Ext.reg('waox.cbChart', WaoX.cbChart);