<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Instalacion</title>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
<link href="<?php echo $this->dir_ext_ccs;?>css/ext-all.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="../../views/js/main/fileuploadfield/css/fileuploadfield.css" rel="stylesheet" type="text/css" media="screen"/>
</head>

<body>
<div id="panel"></div>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-base.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>
<script type="text/javascript" src="../../views/js/main/ns.js"></script> 

<script type="text/javascript" src="../../views/js/main/fileuploadfield/FileUploadField.js"></script>

<script type="text/javascript" src="../../views/js/main/winProgress-ui.js"></script>
<script type="text/javascript" src="../../views/js/main/winProgress.js"></script>


<script type="text/javascript" src="../../views/js/main/winOpenProject-ui.js"></script>
<script type="text/javascript" src="../../views/js/main/winOpenProject.js"></script>

<script type="text/javascript" src="../../views/js/main/winCreateProject-ui.js"></script>
<script type="text/javascript" src="../../views/js/main/winCreateProject.js"></script>

<script type="text/javascript" src="../../views/js/mapper/winMapper-ui.js"></script>
<script type="text/javascript" src="../../views/js/mapper/winMapper.js"></script>

<script type="text/javascript" src="../../views/js/mapper/winRelations-ui.js"></script>
<script type="text/javascript" src="../../views/js/mapper/winRelations.js"></script>


<script type="text/javascript" src="../../views/js/mapper/pRelations-ui.js"></script>
<script type="text/javascript" src="../../views/js/mapper/pRelations.js"></script>

<script type="text/javascript" src="../../views/js/main/main-ui.js"></script> 
<script type="text/javascript" src="../../views/js/main/main.js"></script>
<iframe id='download-iframe'> </iframe>
</body>
</html>
