/*
 * File: MyPanel.ui.js
 * Date: Fri Jan 01 2010 00:02:19 GMT-1100 (Samoa Standard Time)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file was manually exported.
 */

Analizador.UI.frmExcepciones = Ext.extend(Ext.Panel, {
    width: 520,
    height: 385,
    layout: 'column',
    frame: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'fieldset',
                title: 'Generales',
                height: 162,
                columnWidth: 0.5,
                items: [
                    {
                        xtype: 'form',
                        title: '',
                        frame: true,
                        id: 'frm_excepcion',
                        items: [
                            {
                                xtype: 'textfield',
                                fieldLabel: 'Denominaci&oacute;n',
                                anchor: '100%',
                                id: 'denominacion',
                                vtype: 'alphanum',
                                vtypeText : 'Valor inv&aacute;lido',
                                allowBlank : false,
                                maxLength : 50,
                                blankText : 'Debe llenar todos los campos'
                            },
                            {
                                xtype: 'combo',
                                fieldLabel: 'Categor&iacute;a',
                                anchor: '100%',
                                allowBlank : false,
                                editable: false,
                                blankText : 'Debe llenar todos los campos',
                                id: 'categoria',
                                triggerAction :  'all',
                                store : new Ext.data.Store({
                                    url: 'categorias',
                                    reader : new Ext.data.JsonReader ({
                                        root : 'data'
                                    }, ['idcategoria', 'categoria'])
                                }),
                                valueField : 'idcategoria',
                                displayField : 'categoria'
                            },
                            {
                                xtype: 'textfield',
                                fieldLabel: 'Código',
                                anchor: '100%',
                                id: 'codigo',
                                maxLength: 10,
                                vtype: 'alphanum',
                                vtypeText : 'Valor inv&aacute;lido',
                                allowBlank : false,
                                blankText : 'Debe llenar todos los campos'
                            },
                            {
                                xtype: 'textfield',
                                fieldLabel: 'Mensaje',
                                maxLength: 50,
                                anchor: '100%',
                                allowBlank : false,
                                vtype: 'alphanum',
                                vtypeText : 'Valor inv&aacute;lido',
                                blankText : 'Debe llenar todos los campos',
                                id: 'mensaje'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Estructura',
                columnWidth: 0.5,
                height: 162,
                width: 245,
                items: [
                    {
                        xtype: 'treepanel',
                        title: '',
                        id: 'tpEstructura',
                        root: new Ext.tree.AsyncTreeNode({
                            text: 'Tree Node',
                            id : '0'
                        }),
                        rootVisible : false,
                        loader: new Ext.tree.TreeLoader({
                            url : 'estructuras'
                        })
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Respuesta',
                width: 1,
                height: 162,
                columnWidth: 1,
                items: [
                    {
                        xtype: 'form',
                        title: '',
                        items: [
                            {
                                xtype: 'htmleditor',
                                anchor: '100%',
                                id : 'respuesta',
                                fieldLabel: 'Label',
                                hideLabel: true
                            }
                        ]
                    }
                ]
            }
        ];
        Analizador.UI.frmExcepciones.superclass.initComponent.call(this);
    }
});
