/*
 * File: MyPanel.ui.js
 * Date: Fri Jan 01 2010 00:01:05 GMT-1100 (Samoa Standard Time)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file was manually exported.
 */

Analizador.UI.frmRendimiento = Ext.extend(Ext.Panel, {
    title: 'Rendimiento',
    width: 521,
    height: 382,
    layout: 'column',
    frame: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'fieldset',
                title: 'Generales',
                height: 200,
                columnWidth: 0.5,
                items: [
                    {
                        xtype: 'form',
                        title: '',
                        id : 'frm_Rendimiento',
                        frame: true,
                        height: 169,
                        items: [
                            {
                                xtype: 'textfield',
                                fieldLabel: 'Denominaci&oacute;n',
                                anchor: '100%',
                                maxLength: 50,
                                id: 'rdenominacion',
                                vtype: 'alphanum',
                                vtypeText : 'Valor inv&aacute;lido',
                                allowBlank : false,
                                blankText : 'Debe llenar todos los campos'
                            },
                            {
                                xtype: 'combo',
                                fieldLabel: 'Categor&iacute;a',
                                anchor: '100%',
                                editable : true,
                                allowBlank : false,
                                blankText : 'Debe llenar todos los campos',
                                id: 'rcategoria',
                                triggerAction :  'all',
                                blankText : 'Debe llenar todos los campos',
                                allowBlank : false,
                                store : new Ext.data.Store({
                                    url: 'categorias',
                                    reader : new Ext.data.JsonReader ({
                                        root : 'data'
                                    }, ['idcategoria', 'categoria'])
                                }),
                                valueField : 'idcategoria',
                                displayField : 'categoria'
                            },
                            {
                                xtype: 'numberfield',
                                fieldLabel: 'Momoria m&iacute;nima',
                                maxLength: 2,
                                anchor: '100%',
                                maxLength: 5,
                                id: 'rmemoria'
                            },
                            {
                                xtype: 'numberfield',
                                fieldLabel: 'Memoria m&aacute;xima',
                                anchor: '100%',
                                maxLength: 2,
                                id: 'rmemoriamax',
                                maxLength: 5,
                            },
                            {
                                xtype: 'numberfield',
                                maxLength: 5,
                                fieldLabel: 'Tiempo m&iacute;nimo',
                                anchor: '100%',
                                maxLength: 2,
                                id: 'rtiempo'
                            },
                            {
                                xtype: 'numberfield',
                                fieldLabel: 'Tiempo m&aacute;ximo',
                                anchor: '100%',
                                maxLength: 5,
                                id: 'rtiempomax'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Estructura',
                columnWidth: 0.5,
                height: 200,
                width: 245,
                items: [
                    {
                        xtype: 'treepanel',
                        title: '',
                        id: 'tprEstructura',
                        root: new Ext.tree.AsyncTreeNode({
                            text: 'Tree Node',
                            id : '0'
                        }),
                        rootVisible : false,
                        loader: new Ext.tree.TreeLoader({
                            url : 'estructuras'
                        })
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Respuesta',
                columnWidth: 1,
                height: 162,
                items: [
                    {
                        xtype: 'form',
                        title: '',
                        items: [
                            {
                                xtype: 'htmleditor',
                                anchor: '100%',
                                fieldLabel: 'Label',
                                hideLabel: true,
                                id: 'rrespuesta'
                            }
                        ]
                    }
                ]
            }
        ];
        Analizador.UI.frmRendimiento.superclass.initComponent.call(this);
    }
});
