/*
 * File: Analizador.gpRendimiento.ui.js
 * Date: Fri Jan 01 2010 00:04:48 GMT-1100 (Samoa Standard Time)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file was manually exported.
 */

Analizador.UI.gpRendimiento = Ext.extend(Ext.grid.GridPanel, {
    title: 'Rendimiento',
    autoExpandColumn: 'respuesta',
    initComponent: function() {
        this.store = new Ext.data.Store ({
            url : 'Rendimiento',
            reader : new Ext.data.JsonReader({
                root : 'data'
            }, ['denominacion','estructura', 'categoria', 'idestructuracomun', 'idcategoria', 'respuesta', 'tiempomin', 'memoriamin' ,'memoriamax','tiempomax', 'idcaso'])
        })
        
        this.store.load ({
            params: {
                start: 0, limit : 30
            }
        })

        this.winRendimiento = new Analizador.winRendimiento ({
            scope: this
        })

        this.btnAdd = new Ext.Button ({
            scope: this,
            text : 'Adicionar',
            icon: '../../views/img/adicionar.png',
            iconCls:'btn'
        })

        this.btnUpd = new Ext.Button ({
            scope: this,
            text : 'Modificar',
            disabled : true,
            icon: '../../views/img/modificar.png',
            iconCls:'btn'
        })

        this.btnRem = new Ext.Button ({
            scope: this,
            disabled : true,
            text : 'Eliminar',
            icon: '../../views/img/eliminar.png',
            iconCls:'btn'
        })
        
        this.columns = [
            {
                dataIndex: 'denominacion',
                header: 'Denominaci&oacute;n',
                sortable: true,
                width: 100
            },
            {dataIndex: 'estructura',
                header: 'Estructura',
                sortable: true,
                width: 100
            },
            {
                dataIndex: 'categoria',
                header: 'Categor&iacute;a',
                sortable: true,
                width: 100
            },
            {   
                dataIndex: 'respuesta',
                header: 'Respuesta',
                sortable: true,
                width: 100,
                id: 'respuesta'
            },
            {
                dataIndex: 'tiempomin',
                header: 'Tiempo m&iacute;nimo',
                sortable: true,
                width: 100
            },
            {
                dataIndex: 'memoriamin',
                header: 'Memoria m&iacute;nima',
                sortable: true,
                width: 100
            },
            {
                dataIndex: 'tiempomax',
                header: 'Tiempo m&aacute;ximo',
                sortable: true,
                width: 100
            },
            {
                dataIndex: 'memoriamax',
                header: 'Memoria m&aacute;xima',
                sortable: true,
                width: 100
            }
        ];
        
        this.tbar = [
            this.btnAdd, this.btnUpd, this.btnRem
        ];
       
        this.bbar = new Ext.PagingToolbar ({store: this.store, pageSize: 30})
        
        Analizador.UI.gpRendimiento.superclass.initComponent.call(this);
    }
});
