<html>
<head>
<title>SISTEMA INTEGRAL DE GESTI&Oacute;N DE ENTIDADES - CEDRUX</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
<link href="<?php echo $this->dir_ext_ccs;?>css/ext-all.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="<?php echo $this->dir_ext_ccs;?>css/icon-clases.css" rel="stylesheet" type="text/css" media="screen"/>
<link href="<?php echo $this->dir_ext_ccs;?>css/desktop.css" rel="stylesheet" type="text/css" media="screen"/>
<link rel="stylesheet" type="text/css" href="../../views/css/portal/portal.css" />
</head>
<body id="idbodyPortal">
	<div id="bannerPortal" class="bannerPortal" style="display:none">
		<div id="entidadStAccedida" style="visibility:hidden;"></div>
		<div class="bIzq"></div>
		<div class="bDer"></div>
	</div>
	<div id="barraMenu" style="display:none"></div>
	<input type="hidden" id="dir_ext_css" name="dir_extjs" value="<?php echo $this->dir_ext_ccs;?>" />
<div id="cargandoconfiguracion" align="center" style="margin-top:200px;"><img src="../../views/images/portal/cargando.gif"/><br>Por favor espere. Cargando la configuraci&oacute;n de la aplicaci&oacute;n ...</div>
<div id="ux-taskbar">
	<div id="ux-taskbar-start"></div>
	<div id="ux-taskbuttons-panel"></div>
	<div class="x-clear"></div>
</div>
	<div id="x-desktop">	    
		<div id="entidadAccedida" style="visibility:hidden;"></div>
	</div>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-base.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-win-iframe.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/StartMenu.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/TaskBar.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/Desktop.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/App.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/Module.js"></script>
<script type="text/javascript" src="../../views/js/portal/portal.js"></script>
<script type="text/javascript" src="../../views/js/portal/cambiarpassword.js"></script>
</body>
</html>
