/*
 * File: Analizador.gpActivar.ui.js
 * Date: Thu Dec 31 2009 23:01:27 GMT-0800 (Pacific Standard Time)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file was manually exported.
 */

Analizador.UI.gpActivar = Ext.extend(Ext.grid.GridPanel, {
    title: 'Activar an&aacute;lisis',
    autoExpandColumn: 'analisis',
    checkRenderer: function (pValue) {
        if (pValue == 1)
            return "<center><img src = '../../views/img/checked.gif'/> </center>";
        else
            return "<center><img src = '../../views/img/unchecked.gif'/></center>";
    },
    initComponent: function() {
        this.btnActivar = new Ext.Button ({
            scope : this,
            text : 'Activar/Desactivar',
            disabled : true
        })
        
        this.store = new Ext.data.Store ({
           url : 'cargar',
           autoLoad : true,
           reader : new Ext.data.JsonReader({
               root : 'data'
           }, ['name', 'enabled'])
        })
        
        this.columns = [
            {
                dataIndex: 'name',
                header: 'An&aacute;lisis',
                sortable: true,
                id: 'analisis'
            },
            {
                dataIndex: 'enabled',
                header: 'Activado',
                sortable: true,
                renderer: this.checkRenderer
            }
        ];
        this.tbar = [
            this.btnActivar
        ];
        Analizador.UI.gpActivar.superclass.initComponent.call(this);
    }
});
