/*
 * File: Analizador.vpActivar.ui.js
 * Date: Thu Dec 31 2009 23:01:17 GMT-0800 (Pacific Standard Time)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file was manually exported.
 */

Analizador.UI.vpActivar = Ext.extend(Ext.Viewport, {
    layout: 'border',
    initComponent: function() {
        this.items = [
            new Analizador.gpActivar ({
                    region: 'center',
                    scope: this
                })
        ];
        Analizador.UI.vpActivar.superclass.initComponent.call(this);
    }
});
