<html>
<head>
<title>Gestionar Estructura</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style type="text/css">
.nodo {
    background: url(../../views/css/images/cog_edit.png)no-repeat !important;
        }
</style>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
<script language="javascript" type="text/javascript">importarCSS(window.parent.UCID.portal.perfil.dirCss);</script>

</head>
<body>
<div id="element"></div>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-base.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>
<link href="../../css/css/org.css" rel="stylesheet" type="text/css">
<link href="../../css/css/file-upload.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="../../views/js/nomenclador/gestionarnomenclador.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/Organo.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/SubCategorias.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/Nivel_Estructural.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/CargoCivil.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/CargoMilitar.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/CategoriaCivil.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/CategoriaOcupacional.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/Especialidad.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/GradoMilitar.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/PreparacionMilitar.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/TipoCifra.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/Prefijo.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/Tecnica.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/Modulo.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/PreparacionMilitar.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/Agrupacion.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/Calificador.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/EscalaSalarial.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/GrupoComplejidad.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/NivelUtilizacion.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/Salario.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/Tipo DPA.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/DPA.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/FileUploadField.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/Icono.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/Tipo de Calificador.js"></script>
<script type="text/javascript" src="../../views/js/nomenclador/Nomencladores/Clasificacion.js"></script>
</body><div id="organigrama"></div>
</html>