<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Gestionar Sistema"</title>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
<script language="javascript" type="text/javascript">importarCSS(window.parent.UCID.portal.perfil.dirCss);</script>
<link rel="stylesheet" type="text/css" href="../../views/css/gestsistema/file-upload.css" />
</head>

<body>
<form name="exportarsistemas" id="exportarsistemas" method="POST" target="_blank">
    <input type="hidden" name="idsistema" id="idsistema" value=""/>
</form>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-base.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>
<script type="text/javascript" src="../../views/js/gestsistema/FileUploadField.js"></script>
<script type="text/javascript" src="../../views/js/gestsistema/gestsistema.js"></script>
</body>
</html>
