<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DatSistemaCompartimentacion extends BaseDatSistemaCompartimentacion
{
	public function setUp()
	    {
	    parent::setUp();    
	    $this->hasOne('DatSistema',array('local'=>'idsistema','foreign'=>'idsistema')); 
	    }

	static public function obtenerSistemasByIddominio($iddominio) {
			$query = Doctrine_Query::create();
			$datos = $query ->select('idsistema id')
					->from('DatSistemaCompartimentacion')
					->where("iddominio = ?",$iddominio)
					->setHydrationMode( Doctrine :: HYDRATE_ARRAY )
					->execute();
			return $datos;
		}
		
	static public function eliminarSistemas($arraySistEliminar,$iddominio) {
				$query = Doctrine_Query::create();
				$datos = $query ->delete()
						->from('DatSistemaCompartimentacion s')
						->where("s.iddominio = ?",$iddominio)
						->whereIn('s.idsistema',$arraySistEliminar)
						->execute();
				return $datos;
			}
}
