<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SegCompartimentacionusuario extends BaseSegCompartimentacionusuario
{

	public function setUp()
	    {
	    parent::setUp();    
	    $this->hasOne('SegUsuario',array('local'=>'idusuario','foreign'=>'idusuario')); 
	    }

	static public function eliminarUsuarioDominio($idusuario,$iddominio) {
        $query = Doctrine_Query::create();  
        $query->delete()->from('SegCompartimentacionusuario')->where('idusuario =? and iddominio =?',array($idusuario,$iddominio))->execute();
       	return;
    }
    
	static public function cargardominioUsuario($idusuario) {
		$query = Doctrine_Query::create();
		$datos = $query ->select('iddominio')
				->from('SegCompartimentacionusuario')
				->where("idusuario = ?",$idusuario)
				->setHydrationMode( Doctrine :: HYDRATE_ARRAY )
				->execute();
		return $datos;
	}
}