<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SegUsuarioNomDominio extends BaseSegUsuarioNomDominio
{
	public function setUp()
	    {
	    parent::setUp();    
	    $this->hasOne('SegUsuario',array('local'=>'idusuario','foreign'=>'idusuario')); 
	    }

	static public function cargarUsuariosDominios($iddominio) {
		$query = Doctrine_Query::create();
		$datos = $query ->select('idusuario')
				->from('SegUsuarioNomDominio')
				->where("iddominio = ?",$iddominio)
				->setHydrationMode( Doctrine :: HYDRATE_ARRAY )
				->execute();
		return $datos;
	}
}
