<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HisAccion extends BaseHisAccion
{	
	public function setUp ()
	{
		//$this ->hasOne('HisTraza', array ('local' => 'idtraza', 'foreign' => 'idtraza'));
		/*$this ->hasOne('HisRendimiento', array ('local' => 'idtraza', 'foreign' => 'idtraza'));*/		
	}

	public function cantidad($idestructura, $idtipotraza, $idcategoria, $fecha_desde, $fecha_hasta, $campos)
	{
		$where = 't.idtipotraza = ?';
		$valores[] = $idtipotraza;
		if (isset($campos->idusuario) && $campos->idusuario)
		{
			$where .= ' AND t.usuario LIKE ?';
			$valores[] = '%'.$campos->idusuario.'%';
		}
		if (isset($campos->idreferencia) && $campos->idreferencia)
		{
			$where .= ' AND t.referencia LIKE ?';
			$valores[] = '%'.$campos->idreferencia.'%';
		}
		if (isset($campos->idcontrolador) && $campos->idcontrolador)
		{
			$where .= ' AND t.controlador LIKE ?';
			$valores[] = '%'.$campos->idcontrolador.'%';
		}
		if (isset($campos->idaccion) && $campos->idaccion)
		{
			$where .= ' AND t.accion LIKE ?';
			$valores[] = '%'.$campos->idaccion.'%';
		}
		if (isset($campos->idfalla) && ($campos->idfalla == "0" || $campos->idfalla == "1"))
		{
			$where .= ' AND t.falla = ?';
			$valores[] = $campos->idfalla;
		}
		if ($idestructura != 0)
		{
			$where .= ' AND t.idestructuracomun = ?';
			$valores[] = $idestructura;			
		}
		if ($idcategoria != 0)
		{
			$where .= ' AND t.idcategoriatraza = ?';
			$valores[] = $idcategoria;			
		}
		if ($fecha_desde != 0)
		{
			$where .= ' AND t.fecha >= ?';
			$valores[] = $fecha_desde;
		}
		if ($fecha_hasta != 0)
		{
			$where .= ' AND t.fecha <= ?';
			$valores[] = $fecha_hasta;
		}
		$query = Doctrine_Query::create();
		$result = $query->select ('COUNT(t.idtraza) cantidad')
					 ->from('HisAccion t')
					 ->where($where, $valores)
					 ->execute()
					 ->toArray();
		$query->free();
		return $result;
	}
	
	public function select($idestructura, $idtipotraza, $idcategoria, $fecha_desde, $fecha_hasta, $offset, $limit, $campos)
	{ 
		$where = 't.idtipotraza = ?';
		$valores[] = $idtipotraza;
		if (isset($campos->idusuario) && $campos->idusuario)
		{
			$where .= ' AND t.usuario LIKE ?';
			$valores[] = '%'.$campos->idusuario.'%';
		}
		if (isset($campos->idreferencia) && $campos->idreferencia)
		{
			$where .= ' AND t.referencia LIKE ?';
			$valores[] = '%'.$campos->idreferencia.'%';
		}
		if (isset($campos->idcontrolador) && $campos->idcontrolador)
		{
			$where .= ' AND t.controlador LIKE ?';
			$valores[] = '%'.$campos->idcontrolador.'%';
		}
		if (isset($campos->idaccion) && $campos->idaccion)
		{
			$where .= ' AND t.accion LIKE ?';
			$valores[] = '%'.$campos->idaccion.'%';
		}
		if (isset($campos->idfalla) && ($campos->idfalla == "0" || $campos->idfalla == "1"))
		{
			$where .= ' AND t.falla = ?';
			$valores[] = $campos->idfalla;
		}
		if ($idestructura != 0)
		{
			$where .= ' AND t.idestructuracomun = ?';
			$valores[] = $idestructura;			
		}
		if ($idcategoria != 0)
		{
			$where .= ' AND t.idcategoriatraza = ?';
			$valores[] = $idcategoria;			
		}
		if ($fecha_desde != 0)
		{
			$where .= ' AND t.fecha >= ?';
			$valores[] = $fecha_desde;
		}
		if ($fecha_hasta != 0)
		{
			$where .= ' AND t.fecha <= ?';
			$valores[] = $fecha_hasta;
		}
		
		$query = Doctrine_Query::create();
		$result = $query->select('t.idtraza, t.fecha, t.hora, t.usuario, t.idestructuracomun, t.referencia, t.controlador, t.accion, t.inicio, t.falla')
					 	 ->from('HisAccion t')
					  	 ->where($where, $valores)
					  	 ->offset($offset)
					  	 ->limit($limit)
						 ->execute()
						 ->toArray();
		$query->free();
		return $result;
	}
}