<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HisExcepcion extends BaseHisExcepcion
{
	public function cantidad($idestructura, $idtipotraza, $idcategoria, $fecha_desde, $fecha_hasta, $campos)
	{
		$count = 0;
		$where = 't.idtipotraza = ?';
		$valores[$count] = $idtipotraza;
		if (isset($campos->idusuario) && $campos->idusuario)
		{
			$count++;
			$where .= ' AND t.usuario LIKE ?';
			$valores[$count] = '%'.$campos->idusuario.'%';
		}
		if ($idestructura != 0)
		{
			$count++;
			$where .= ' AND t.idestructuracomun = ?';
			$valores[$count] = $idestructura;			
		}
		if ($idcategoria != 0)
		{
			$count++;
			$where .= ' AND t.idcategoriatraza = ?';
			$valores[$count] = $idcategoria;			
		}
		if ($fecha_desde != 0)
		{
			$count++;
			$where .= ' AND t.fecha >= ?';
			$valores[$count] = $fecha_desde;
		}
		if ($fecha_hasta != 0)
		{
			$count++;
			$where .= ' AND t.fecha <= ?';
			$valores[$count] = $fecha_hasta;
		}
		$query = Doctrine_Query::create();
		$result = $query->select ('COUNT(t.idtraza) cantidad')
					 ->from('HisExcepcion t')
					 ->where($where, $valores)
					 ->execute()
					 ->toArray();
		$query->free();
		return $result;
	}
	
	public function select($idestructura, $idtipotraza, $idcategoria, $fecha_desde, $fecha_hasta, $offset, $limit, $campos)
	{ 
		$count = 0;
		$where = 't.idtipotraza = ?';
		$valores[$count] = $idtipotraza;
		if (isset($campos->idusuario) && $campos->idusuario)
		{
			$count++;
			$where .= ' AND t.usuario LIKE ?';
			$valores[$count] = '%'.$campos->idusuario.'%';
		}
		if ($idestructura != 0)
		{
			$count++;
			$where .= ' AND t.idestructuracomun = ?';
			$valores[$count] = $idestructura;			
		}
		if ($idcategoria != 0)
		{
			$count++;
			$where .= ' AND t.idcategoriatraza = ?';
			$valores[$count] = $idcategoria;			
		}
		if ($fecha_desde != 0)
		{
			$count++;
			$where .= ' AND t.fecha >= ?';
			$valores[$count] = $fecha_desde;
		}
		if ($fecha_hasta != 0)
		{
			$count++;
			$where .= ' AND t.fecha <= ?';
			$valores[$count] = $fecha_hasta;
		}
		$query = Doctrine_Query::create();
		$result = $query->select('t.idtraza, t.fecha, t.hora, t.usuario, t.idestructuracomun, t.codigo, t.tipo, t.idioma, t.mensaje, t.descripcion, t.log')
				 	 ->from('HisExcepcion t')
				  	 ->where($where, $valores)
				  	 ->offset($offset)
				  	 ->limit($limit)
					 ->execute()->toArray();
		$query->free();
		return $result;
	}
}