<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NomTipotraza extends BaseNomTipotraza
{
	function setUp ()
	{
		$this->hasMany ('HiTraza', array ('local' => 'idtipotraza',
										  'foreign' => 'idtipotraza'));
	}
	
	static public function selectAlltipo()
	{
		$query = Doctrine_Query::create();
		return  $query->select('t.idtipotraza, t.tipotraza')
						->from('NomTipotraza t')
						->execute()->toArray();
	}
}
?>