<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Gestionar servicios web</title>
        <script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
        <link href="<?php echo $this->dir_ext_ccs;?>css/ext-all.css" rel="stylesheet" type="text/css" media="screen"/>
    </head>

    <body>
        <script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-base.js"></script>
        <script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-all.js"></script>
        <script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>

        <script type="text/javascript" src="../../views/js/gestwebservice/ns.js"></script>
        <script type="text/javascript" src="../../views/js/gestwebservice/RowExpander.js"></script>

        <script type="text/javascript" src="../../views/js/gestwebservice/wNewPackage-ui.js"></script>
        <script type="text/javascript" src="../../views/js/gestwebservice/wNewPackage.js"></script>

        <script type="text/javascript" src="../../views/js/gestwebservice/wNewService-ui.js"></script>
        <script type="text/javascript" src="../../views/js/gestwebservice/wNewService.js"></script>

        <script type="text/javascript" src="../../views/js/gestwebservice/tpIoC-ui.js"></script>
        <script type="text/javascript" src="../../views/js/gestwebservice/tpIoC.js"></script>

        <script type="text/javascript" src="../../views/js/gestwebservice/gpPackage-ui.js"></script>
        <script type="text/javascript" src="../../views/js/gestwebservice/gpPackage.js"></script>

        <script type="text/javascript" src="../../views/js/gestwebservice/gpError-ui.js"></script>
        <script type="text/javascript" src="../../views/js/gestwebservice/gpError.js"></script>

        <script type="text/javascript" src="../../views/js/gestwebservice/wDocblockEditor-ui.js"></script>
        <script type="text/javascript" src="../../views/js/gestwebservice/wDocblockEditor.js"></script>

        <script type="text/javascript" src="../../views/js/gestwebservice/project-ui.js"></script>
        <script type="text/javascript" src="../../views/js/gestwebservice/project.js"></script>
    </body>
</html>
