<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html;  charset=utf-8" />
		<title>Arbol con estructuras</title>
		<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
		<script language="javascript" type="text/javascript">importarCSS(window.parent.parent.UCID.portal.perfil.dirCss);</script>
	</head>
	<!-- -->
	<body>
		<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-base.js"></script>
		<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-all.js"></script>
		<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>
		<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-integra-interfaz.js"></script>
		<script type="text/javascript" src="../../views/js/estructuratree/estructuratree.js"></script>
	</body>
</html>
