<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Instalacion</title>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
<link href="../../views/js/extjs/resources/css/ext-all.css" rel="stylesheet" type="text/css" media="screen"/>
</head>

<body>
<div id="panel"></div>
<script type="text/javascript" src="../../views/js/extjs/ext-base.js"></script>
<script type="text/javascript" src="../../views/js/extjs/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>

<script type="text/javascript" src="../../views/js/message-bus/strophe.min.js"></script> 
<script type="text/javascript" src="../../views/js/message-bus/Componentes.MessageBus.js"></script> 

<script type="text/javascript" src="../../views/js/waox/WaoX.stCBChart.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.stView.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.stChart.js"></script> 

<script type="text/javascript" src="../../views/js/waox/charts/WaoX.chrBarChart.js"></script> 
<script type="text/javascript" src="../../views/js/waox/charts/WaoX.chrColumnChart.js"></script> 
<script type="text/javascript" src="../../views/js/waox/charts/WaoX.chrPieChart.js"></script> 
<script type="text/javascript" src="../../views/js/waox/charts/WaoX.chrTableChart.js"></script>
<script type="text/javascript" src="../../views/js/waox/charts/WaoX.chrLineChart.js"></script>
<script type="text/javascript" src="../../views/js/waox/charts/WaoX.chrCartesianChart.js"></script> 

<script type="text/javascript" src="../../views/js/waox/WaoX.btnAdd.ui.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.btnAdd.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.btnRemove.ui.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.btnRemove.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.cbChart.ui.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.cbChart.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.cbView.ui.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.cbView.js"></script>
<script type="text/javascript" src="../../views/js/waox/WaoX.egChart.ui.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.egChart.js"></script>
<script type="text/javascript" src="../../views/js/waox/WaoX.winNew.ui.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.winNew.js"></script>
<script type="text/javascript" src="../../views/js/waox/WaoX.winConfiguration.ui.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.winConfiguration.js"></script>

<script type="text/javascript" src="../../views/js/waox/WaoX.btnNew.ui.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.btnNew.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.pBase.ui.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.pBase.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.vpWaox.ui.js"></script> 
<script type="text/javascript" src="../../views/js/waox/WaoX.vpWaox.js"></script> 

<script type="text/javascript" src="../../views/js/waox/waox.js"></script> 
</body>
</html>