<html>
<head>
<title>Gestionar Estructura</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
<script language="javascript" type="text/javascript">importarCSS(window.parent.UCID.portal.perfil.dirCss);</script>
</head>
<body>
<div id="element"></div>
<link href="../../css/css/org.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-base.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>
<script type="text/javascript" src="../../views/js/estructurasb/ucid-win-iframe.js"></script>
<script type="text/javascript" src="../../views/js/estructurasb/GenDinamico.js"></script>
<!--<script type="text/javascript" src="../../views/js/estructurasb/gest_Puestos.js"></script>
<script type="text/javascript" src="../../views/js/estructurasb/gest_Medios.js"></script>
<script type="text/javascript" src="../../views/js/estructurasb/gestionarCargo.js"></script>
<script type="text/javascript" src="../../views/js/estructurasb/gest_Agrupacion.js"></script>-->
<script type="text/javascript" src="../../views/js/estructurasb/gestionarestructura.js"></script>




</body><div id="organigrama"></div>
</html>