<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Instalacion</title>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
<link href="<?php echo $this->dir_ext_ccs;?>css/ext-all.css" rel="stylesheet" type="text/css" media="screen"/>
</head>

<body>
<div id="panel"></div>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-base.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>

<script type="text/javascript" src="../../views/js/caso/ns.js"></script>

<script type="text/javascript" src="../../views/js/respuesta/gpRespuesta.ui.js"></script>
<script type="text/javascript" src="../../views/js/respuesta/gpRespuesta.js"></script>

<script type="text/javascript" src="../../views/js/respuesta/vpRespuesta.ui.js"></script>
<script type="text/javascript" src="../../views/js/respuesta/vpRespuesta.js"></script>
</body>
</html>
