<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
<script language="javascript" type="text/javascript">importarCSS(window.parent.UCID.portal.perfil.dirCss);</script>
<title>Organigrama</title>
<link type="text/css" rel="stylesheet" href="../../views/css/css/ECOTree.css" />
</head>
<body>
<div id="panel"></div>
<div id="hello-win"  ></div>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-base.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-all.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-win-iframe.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/dinamic_report.js"></script>
<script type="text/javascript" src="../../views/js/reportes/ECOTree.js"></script>
<script type="text/javascript" src="../../views/js/reportes/reporte.js"></script>
</body>
</html>
