<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Funcionalidad extends BaseFuncionalidad
{
	public function setUp ()
	{
		$this->hasOne('Modulo', array('local'=>'idmodulo', 'foreign'=>'idmodulo'));
	}
}
