<html>
<head>
    <title>Gestor Principal</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
    <script language="javascript" type="text/javascript">importarCSS(window.parent.UCID.portal.perfil.dirCss);</script>
</head>
<body>
    <form name="donwloadproxy" id="donwloadproxy" method="POST" target="_blank">
        <input type="hidden" name="idproxies" id="idproxies" value=""/>
    </form>
    <script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-base.js"></script>
    <script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-all.js"></script>
    <script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/RowExpander.js"></script>
    <script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>

    <script type="text/javascript" src= "../../views/js/compiler/tree.js"></script>
    
    <script type="text/javascript" src= "../../views/js/compiler/gestprincipal.js"></script>
    

    
</body>
</html>
