<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Gestionar tipos de datos</title>
        <script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/imporcss.js"></script>
        <link href="<?php echo $this->dir_ext_ccs;?>css/ext-all.css" rel="stylesheet" type="text/css" media="screen"/>
    </head>

    <body>
        <script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-base.js"></script>
        <script type="text/javascript" src="<?php echo $this->dir_extjs;?>js/ext-all.js"></script>
        <script type="text/javascript" src="<?php echo $this->dir_ucid;?>js/ucid-all.js"></script>

        <script type="text/javascript" src="../../views/js/gestwebservice/ns.js"></script>

        <script type="text/javascript" src="../../views/js/gestdatatype/wAddDatatype-ui.js"></script>
        <script type="text/javascript" src="../../views/js/gestdatatype/wAddDatatype.js"></script>

        <script type="text/javascript" src="../../views/js/gestdatatype/wAddField-ui.js"></script>
        <script type="text/javascript" src="../../views/js/gestdatatype/wAddField.js"></script>

        <script type="text/javascript" src="../../views/js/gestdatatype/vpDatatype-ui.js"></script>
        <script type="text/javascript" src="../../views/js/gestdatatype/vpDatatype.js"></script>
    </body>
</html>
